### ISSUE TITLE
[Enhancement] [Track] Dora WASM Compiler

### ISSUE THREAD

**Issue by timi-y** [dp-labs/dora#6]
## Tasks

+ [x] Complete the implementation and end-to-end testing of all operators, WASM Operator -> WASM Dialect -> Dora Dialect (Note: We will not support SIMD related operators, the code is [here](https://github.com/dp-labs/dora/blob/main/crates/dora-compiler/src/wasm/code.rs), and the test is [here](https://github.com/dp-labs/dora/tree/main/crates/dora-compiler/src/wasm/tests))
  + [x] add @timi-y 
  + [x] sub @timi-y 
  + [x] div_u @timi-y 
  + [x] div_s @timi-y 
  + [x] rem_u @timi-y 
  + [x] rem_s @timi-y 
  + [x] and @ldxdl 
  + [x] or @ldxdl 
  + [x] xor @ldxdl 
  + [x] shl @ldxdl 
  + [x] shr_s @ldxdl 
  + [x] shr_u @ldxdl 
  + [x] rotl @ldxdl 
  + [x] rotr @ldxdl 
  + [x] clz @ldxdl 
  + [x] ctz @ldxdl 
  + [x] popcnt @ldxdl 
  + [x] extend8_s @ldxdl 
  + [x] extend16_s @ldxdl 
  + [x] extend32_s @ldxdl 
  + [x] eqz @ldxdl 
  + [x] eq @ldxdl 
  + [x] ne @ldxdl 
  + [x] lt_s @timi-y 
  + [x] lt_u @timi-y 
  + [x] le_s @timi-y 
  + [x] le_u @timi-y 
  + [x] gt_s @timi-y 
  + [x] gt_u @timi-y 
  + [x] ge_s @timi-y 
  + [x] ge_u @timi-y 
  + [x] ceil @ldxdl 
  + [x] abs @ldxdl 
  + [x] neg @ldxdl 
  + [x] floor @ldxdl 
  + [x] trunc @ldxdl 
  + [x] nearest @ldxdl 
  + [x] sqrt @timi-y
  + [x] copysign @ldxdl 
  + [x] nop @timi-y 
  + [x] unreachable @timi-y 
  + [x] block @timi-y 
  + [x] loop @timi-y 
  + [x] if @timi-y 
  + [x] else @timi-y 
  + [x] end @timi-y 
  + [x] br @timi-y 
  + [x] brif @timi-y 
  + [x] brtable @timi-y 
  + [x] return @timi-y 
  + [x] call @timi-y 
  + [x] returncall @timi-y 
  + [x] returncallindirect @timi-y 
  + [x] drop @timi-y 
  + [x] select @timi-y 
  + [x] typedselect @timi-y 
  + [x] local.get @timi-y 
  + [x] local.set @timi-y 
  + [x] local.tee @timi-y 
  + [x] global.get @timi-y 
  + [x] global.set @timi-y 
  + [x] i32.load @timi-y 
  + [x] i64.load @timi-y 
  + [x] i32.load8s @timi-y 
  + [x] i32.load8u @timi-y 
  + [x] i32.load16s @timi-y 
  + [x] i32.load16u @timi-y 
  + [x] i64.load8s @timi-y 
  + [x] i64.load8u @timi-y 
  + [x] i64.load16s @timi-y 
  + [x] i64.load16u @timi-y 
  + [x] i32.store @timi-y 
  + [x] i64.store @timi-y 
  + [x] i32.store8 @timi-y 
  + [x] i32.store16 @timi-y 
  + [x] i64.store8 @timi-y 
  + [x] i64.store16 @timi-y 
  + [x] i32.const @timi-y 
  + [x] i64.const @timi-y 
  + [x] f32.const @timi-y 
  + [x] f64.const @timi-y 
  + [x] refnull @timi-y 
  + [x] refisnull @timi-y 
  + [x] reffunc @timi-y 
  + [x] refeq @timi-y 
  + [x] trunc releated operators, e.g., i32.trunc.f64u, f64.convert.i64u, ...  @timi-y 
+ [x] Complete the translation of all EVM related Host APIs such as storage read/write, block env, etc. into Dora Dialect https://github.com/dp-labs/dora/pull/300
  + [x] fn code_size(address: *const u8) -> usize;
  + [x] fn code(address: *const u8, offset: usize, size: usize, dest: *mut u8) -> usize;
  + [x] fn codehash(address: *const u8, dest: *mut u8);
  + [x] fn emit_log(data: *const u8, len: usize, topics: usize);
  + [x] fn address(address: *mut u8);
  + [x] fn gas_left() -> u64;
  + [x] fn gas_limit() -> u64;
  + [x] fn chainid() -> u64;
  + [x] fn balance(address: *const u8, dest: *mut u8);
  + [x] fn basefee(basefee: *mut u8);
  + [x] fn coinbase(coinbase: *mut u8);
  + [x] fn msg_sender(sender: *mut u8);
  + [x] fn msg_value(value: *mut u8);
  + [x] fn sload(address: *const u8, key: *const u8, dest: *mut u8);
  + [x] fn sstore(address: *const u8, key: *const u8, value: *const u8);
  + [x] fn tload(address: *const u8, key: *const u8, dest: *mut u8);
  + [x] fn tstore(address: *const u8, key: *const u8, value: *const u8);
  + [x] fn keccak256(bytes: *const u8, len: usize, output: *mut u8);
  + [x] fn read_call_data(dest: *mut u8);
  + [x] fn read_return_data(dest: *mut u8, offset: usize, size: usize) -> usize;
  + [x] fn write_result(data: *const u8, len: usize);
  + [x] fn call(contract: *const u8, calldata: *const u8, calldata_len: usize, value: *const u8, gas: u64, return_data_len: *mut usize) -> u8;
  + [x] fn delegate_call(contract: *const u8, calldata: *const u8, calldata_len: usize, gas: u64, return_data_len: *mut usize) -> u8;
  + [x] fn static_call(contract: *const u8, calldata: *const u8, calldata_len: usize, gas: u64, return_data_len: *mut usize) -> u8;
  + [x] fn create(code: *const u8, code_len: usize, endowment: *const u8, contract: *mut u8, revert_data_len: *mut usize);
  + [x] fn create2(code: *const u8, code_len: usize, endowment: *const u8, salt: *const u8, contract: *mut u8, revert_data_len: *mut usize);
  + [x] fn gas_price(price: *mut u8);
  + [x] fn origin(origin: *mut u8);
+ [x] #305
+ [x] #306
+ [x] #307
 
## Reference

+ WASM Spec Test: https://github.com/WebAssembly/spec/tree/main/test/core
+ Wasmer LLVM Backend: https://github.com/wasmerio/wasmer/tree/main/lib/compiler-llvm
